<a href="https://colab.research.google.com/github/Nurs0305n/Python/blob/main/IntelligentWSystemsAndTechnologies/firstWork/hw_5_numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Задача 1: Создание массивов с помощью NumPy

NumPy предоставляет множество функций для создания массивов. Ваша задача - использовать эти функции для создания и манипуляции массивами.


Создайте одномерный массив размером 20, заполненный нулями.
Ожидаемый результат: Одномерный массив размером 20, все элементы которого равны нулю.


In [ ]:
# место для ответа
import numpy as np
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

Создайте двумерный массив размером 3x3, заполненный единицами.
Ожидаемый результат: Двумерный массив 3x3, все элементы которого равны единице.


In [ ]:
# место для ответа
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Создайте массив размером 4x4, заполненный числом π.
Ожидаемый результат: Массив 4x4, все элементы которого равны π.


In [ ]:
# место для ответа
np.full((4, 4), 2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

Создайте одномерный массив, содержащий последовательность чисел от 0 до 100 с шагом 5.
Ожидаемый результат: Массив, содержащий числа: 0, 5, 10, ..., 100.


In [ ]:
# место для ответа
np.arange(0, 100, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

Создайте двумерный массив 5x5, в котором на главной диагонали стоят числа от 1 до 5, а все остальные элементы равны нулю.
Ожидаемый результат: Массив 5x5, на главной диагонали которого числа от 1 до 5, а все остальные элементы равны нулю.

In [ ]:
# место для ответа
a = np.zeros((5, 5))
a[0, 0] = 1
a[1, 1] = 2
a[2, 2] = 3
a[3, 3] = 4
a[4, 4] = 5
print(a)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


# Задача 2: Использование NumPy для генерации случайных чисел

NumPy предоставляет множество функций для генерации случайных чисел. Ваша задача - использовать эти функции для создания массивов и выполнения операций над ними.

Создайте одномерный массив из 10 случайных чисел в интервале от 0 до 1.
Ожидаемый результат: Массив из 10 случайных чисел.

In [ ]:
# место для ответа

np.random.random_sample(10)

array([0.18075443, 0.10981401, 0.52415454, 0.65389573, 0.52307784,
       0.10304788, 0.29100404, 0.08086636, 0.88975308, 0.42385278])

Создайте двумерный массив размером 3x3, содержащий случайные числа от 0 до 1.
Ожидаемый результат: Массив 3x3 со случайными числами.

In [ ]:
# место для ответа
np.random.random_sample((3,3))

array([[0.42008468, 0.97202398, 0.82620822],
       [0.56844773, 0.9447301 , 0.44153781],
       [0.80882906, 0.40838506, 0.37734561]])

Создайте одномерный массив из 20 случайных целых чисел в интервале от 1 до 10.
Ожидаемый результат: Массив из 20 случайных целых чисел в интервале от 1 до 10.

In [ ]:
# место для ответа
np.random.randint(1,10, 20)

array([2, 1, 4, 7, 2, 3, 5, 5, 1, 2, 6, 9, 3, 7, 7, 7, 4, 3, 1, 1])

Функция `np.random.seed()` используется для инициализации генератора случайных чисел. Вы можете использовать любое целое число в качестве "семени". Ваша задача - использовать эту функцию для контроля генерации случайных чисел.

Задайте семя генератора случайных чисел, используя np.random.seed(0), и сгенерируйте одномерный массив из 5 случайных чисел в интервале от 0 до 1. Запишите результат.
Ожидаемый результат: Одномерный массив из 5 случайных чисел.

In [34]:
# место для ответа
np.random.seed(0)
np.random.random(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

Затем еще раз задайте семя генератора случайных чисел, используя ту же команду `np.random.seed(0)`, и снова сгенерируйте одномерный массив из 5 случайных чисел в интервале от 0 до 1. Сравните результат с полученным в первом шаге.
Ожидаемый результат: Одномерный массив из 5 случайных чисел, который должен быть идентичен массиву, полученному в первом шаге.

In [35]:
# место для ответа
np.random.seed(0)
np.random.random(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

Теперь задайте семя генератора случайных чисел с другим значением, например, `np.random.seed(1)`, и сгенерируйте одномерный массив из 5 случайных чисел в интервале от 0 до 1. Сравните результат с полученными ранее.
Ожидаемый результат: Одномерный массив из 5 случайных чисел, который отличается от массивов, полученных в предыдущих шагах.

In [38]:
# место для ответа
np.random.seed(1)
np.random.random(5)

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01])

# Задача 3: Выполнение векторных операций с помощью NumPy

NumPy позволяет выполнять векторные операции над массивами без необходимости использовать циклы. Ваша задача - использовать NumPy для выполнения следующих векторных операций.

Создайте два одномерных массива размером 10, содержащих случайные числа. Выполните поэлементное сложение этих двух массивов.
Ожидаемый результат: Одномерный массив размером 10, содержащий сумму элементов двух исходных массивов.

In [48]:
# место для ответа
array1 = np.random.randint(0, 10, 10)
array2 = np.random.randint(0, 10, 10)

array1 + array2

array([17,  9, 11,  3,  9, 14,  3,  9,  7, 13])

Используйте один из созданных массивов и возведите все его элементы в квадрат.
Ожидаемый результат: Одномерный массив, все элементы которого возведены в квадрат.

In [56]:
# место для ответа
array2**2

array([64,  1, 16,  0,  9, 81,  4,  0, 16, 81])

Создайте два двумерных массива размером 3x3, содержащих случайные числа. Выполните поэлементное умножение этих двух массивов.
Ожидаемый результат: Двумерный массив 3x3, содержащий произведение элементов двух исходных массивов.

In [57]:
# место для ответа
a = np.random.randint(0,10,(3,3))
b = np.random.randint(0,10,(3,3))

a*b

array([[14, 28, 35],
       [81, 24, 36],
       [72,  0, 14]])

Используйте один из созданных двумерных массивов и вычислите среднее значение всех его элементов.
Ожидаемый результат: Число, представляющее среднее значение всех элементов массива.

In [62]:
# место для ответа
np.mean(a)

6.444444444444445

Создайте одномерный массив, содержащий последовательность чисел от 1 до 10, и вычислите кумулятивную сумму его элементов.
Ожидаемый результат: Одномерный массив, содержащий кумулятивную сумму элементов исходного массива.

In [68]:
# место для ответа
c = np.arange(1, 11, 1)
np.cumsum(c)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

# Задача 4: Вычисление минимального, максимального и стандартного отклонения с помощью NumPy

NumPy предоставляет функции для вычисления минимального и максимального значений, а также стандартного отклонения элементов массива. Ваша задача - использовать эти функции для анализа данных в массивах.

Создайте одномерный массив из 20 случайных чисел. Найдите минимальное и максимальное значение в этом массиве.
Ожидаемый результат: Минимальное и максимальное значения массива.

In [72]:
# место для ответа
a = np.random.randint(0, 100, 20)
print(a.min())
print(a.max())

7
97


Используйте тот же одномерный массив и вычислите стандартное отклонение его элементов.
Ожидаемый результат: Стандартное отклонение элементов массива.

In [73]:
# место для ответа
print(a.std())

32.74885494181438


Создайте двумерный массив размером 5x5 из случайных чисел. Найдите минимальное и максимальное значение в этом массиве.
Ожидаемый результат: Минимальное и максимальное значения массива.



In [80]:
# место для ответа
a = np.random.randint(0, 100, (5, 5))
print(a.min())
print(a.max())
print(a)

0
92
[[70 25 48 50 62]
 [44 54  0 86 16]
 [19  9 92 51 10]
 [68 23 14 63 21]
 [46  3 56 88 80]]


Используйте этот же двумерный массив и вычислите стандартное отклонение его элементов.
Ожидаемый результат: Стандартное отклонение элементов массива.



In [81]:
# место для ответа
a.std()

27.730012621706468

Найдите минимальное и максимальное значение, а также стандартное отклонение вдоль каждого столбца двумерного массива.
Ожидаемый результат: Минимальное и максимальное значение, а также стандартное отклонение для каждого столбца массива.

In [82]:
# место для ответа
print(np.min(a, 0))
print(np.max(a, 1))

[19  3  0 50 10]
[70 86 92 68 88]


# Задача 5: Сортировка и нахождение уникальных значений с помощью NumPy

NumPy предлагает функции для сортировки элементов массива и нахождения уникальных значений. Ваша задача - использовать эти функции для работы с данными в массивах.

Создайте одномерный массив из 10 случайных целых чисел от 1 до 20. Отсортируйте этот массив в порядке возрастания.
Ожидаемый результат: Отсортированный массив из 10 случайных чисел.

In [83]:
# место для ответа
a = np.random.randint(0, 20, 10)
np.sort(a)

array([ 5,  7, 12, 13, 14, 14, 14, 15, 15, 18])

Используя тот же одномерный массив, найдите все уникальные элементы этого массива.
Ожидаемый результат: Массив, содержащий все уникальные элементы исходного массива.

In [84]:
# место для ответа
np.unique(a)

array([ 5,  7, 12, 13, 14, 15, 18])

# Задача 6: Использование операторов сравнения и тестирование значений с NumPy

NumPy предоставляет операторы для сравнения элементов массива и проверки определенных условий. Ваша задача - использовать эти функции для анализа данных в массивах.

Создайте одномерный массив из 10 случайных чисел от 1 до 100. Создайте булев массив, который будет содержать `True` для всех элементов исходного массива, которые больше 50, и `False` - для всех остальных.
Ожидаемый результат: Булев массив размером 10.

In [94]:
# место для ответа
a = np.random.randint(0, 100, (5, 5))
b = a > 50
print(b)

[[ True False  True False False]
 [False False  True False  True]
 [ True False  True False  True]
 [False False False  True  True]
 [False False False False  True]]


Используя созданный булев массив, выберите из исходного массива только те элементы, которые больше 50.
Ожидаемый результат: Массив элементов исходного массива, которые больше 50.

In [95]:
# место для ответа
a[b]

array([58, 92, 96, 87, 75, 63, 91, 97, 70, 52])

# Бонус задание

Создайте двумерный массив размером 5x5 из случайных чисел от 1 до 50. Создайте булев массив, который будет содержать True для всех элементов исходного массива, которые четные, и False - для всех остальных.
Ожидаемый результат: Булев массив размером 5x5.

In [98]:
# место для ответа
d = np.random.randint(0, 50, (5, 5))
e = d % 2 == 0
print(e)

[[ True  True  True  True False]
 [ True  True  True  True  True]
 [False  True False  True False]
 [ True False False False  True]
 [ True False False False False]]


Используя созданный булев массив, выберите из исходного массива только те элементы, которые четные.
Ожидаемый результат: Массив элементов исходного массива, которые четные.

In [99]:
# место для ответа
d[e]

array([ 2, 12, 32, 32, 36, 10, 12, 18, 30, 16, 32, 44, 44, 24])