<a href="https://colab.research.google.com/github/Nurs0305n/Python/blob/main/hw_5_numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Задача 1: Создание массивов с помощью NumPy

NumPy предоставляет множество функций для создания массивов. Ваша задача - использовать эти функции для создания и манипуляции массивами.


Создайте одномерный массив размером 20, заполненный нулями.
Ожидаемый результат: Одномерный массив размером 20, все элементы которого равны нулю.


In [ ]:
# место для ответа
import numpy as np
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

Создайте двумерный массив размером 3x3, заполненный единицами.
Ожидаемый результат: Двумерный массив 3x3, все элементы которого равны единице.


In [ ]:
# место для ответа
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Создайте массив размером 4x4, заполненный числом π.
Ожидаемый результат: Массив 4x4, все элементы которого равны π.


In [ ]:
# место для ответа
np.full((4, 4), 2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

Создайте одномерный массив, содержащий последовательность чисел от 0 до 100 с шагом 5.
Ожидаемый результат: Массив, содержащий числа: 0, 5, 10, ..., 100.


In [ ]:
# место для ответа


Создайте двумерный массив 5x5, в котором на главной диагонали стоят числа от 1 до 5, а все остальные элементы равны нулю.
Ожидаемый результат: Массив 5x5, на главной диагонали которого числа от 1 до 5, а все остальные элементы равны нулю.

In [ ]:
# место для ответа

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# Задача 2: Использование NumPy для генерации случайных чисел

NumPy предоставляет множество функций для генерации случайных чисел. Ваша задача - использовать эти функции для создания массивов и выполнения операций над ними.

Создайте одномерный массив из 10 случайных чисел в интервале от 0 до 1.
Ожидаемый результат: Массив из 10 случайных чисел.

In [ ]:
# место для ответа


Создайте двумерный массив размером 3x3, содержащий случайные числа от 0 до 1.
Ожидаемый результат: Массив 3x3 со случайными числами.

In [ ]:
# место для ответа


Создайте одномерный массив из 20 случайных целых чисел в интервале от 1 до 10.
Ожидаемый результат: Массив из 20 случайных целых чисел в интервале от 1 до 10.

In [ ]:
# место для ответа


Функция `np.random.seed()` используется для инициализации генератора случайных чисел. Вы можете использовать любое целое число в качестве "семени". Ваша задача - использовать эту функцию для контроля генерации случайных чисел.

Задайте семя генератора случайных чисел, используя np.random.seed(0), и сгенерируйте одномерный массив из 5 случайных чисел в интервале от 0 до 1. Запишите результат.
Ожидаемый результат: Одномерный массив из 5 случайных чисел.

In [ ]:
# место для ответа


Затем еще раз задайте семя генератора случайных чисел, используя ту же команду `np.random.seed(0)`, и снова сгенерируйте одномерный массив из 5 случайных чисел в интервале от 0 до 1. Сравните результат с полученным в первом шаге.
Ожидаемый результат: Одномерный массив из 5 случайных чисел, который должен быть идентичен массиву, полученному в первом шаге.

In [ ]:
# место для ответа


Теперь задайте семя генератора случайных чисел с другим значением, например, `np.random.seed(1)`, и сгенерируйте одномерный массив из 5 случайных чисел в интервале от 0 до 1. Сравните результат с полученными ранее.
Ожидаемый результат: Одномерный массив из 5 случайных чисел, который отличается от массивов, полученных в предыдущих шагах.

In [ ]:
# место для ответа


# Задача 3: Выполнение векторных операций с помощью NumPy

NumPy позволяет выполнять векторные операции над массивами без необходимости использовать циклы. Ваша задача - использовать NumPy для выполнения следующих векторных операций.

Создайте два одномерных массива размером 10, содержащих случайные числа. Выполните поэлементное сложение этих двух массивов.
Ожидаемый результат: Одномерный массив размером 10, содержащий сумму элементов двух исходных массивов.

In [ ]:
# место для ответа


Используйте один из созданных массивов и возведите все его элементы в квадрат.
Ожидаемый результат: Одномерный массив, все элементы которого возведены в квадрат.

In [ ]:
# место для ответа


Создайте два двумерных массива размером 3x3, содержащих случайные числа. Выполните поэлементное умножение этих двух массивов.
Ожидаемый результат: Двумерный массив 3x3, содержащий произведение элементов двух исходных массивов.

In [ ]:
# место для ответа


Используйте один из созданных двумерных массивов и вычислите среднее значение всех его элементов.
Ожидаемый результат: Число, представляющее среднее значение всех элементов массива.

In [ ]:
# место для ответа


Создайте одномерный массив, содержащий последовательность чисел от 1 до 10, и вычислите кумулятивную сумму его элементов.
Ожидаемый результат: Одномерный массив, содержащий кумулятивную сумму элементов исходного массива.

In [ ]:
# место для ответа


# Задача 4: Вычисление минимального, максимального и стандартного отклонения с помощью NumPy

NumPy предоставляет функции для вычисления минимального и максимального значений, а также стандартного отклонения элементов массива. Ваша задача - использовать эти функции для анализа данных в массивах.

Создайте одномерный массив из 20 случайных чисел. Найдите минимальное и максимальное значение в этом массиве.
Ожидаемый результат: Минимальное и максимальное значения массива.

In [ ]:
# место для ответа


Используйте тот же одномерный массив и вычислите стандартное отклонение его элементов.
Ожидаемый результат: Стандартное отклонение элементов массива.

In [ ]:
# место для ответа


Создайте двумерный массив размером 5x5 из случайных чисел. Найдите минимальное и максимальное значение в этом массиве.
Ожидаемый результат: Минимальное и максимальное значения массива.



In [ ]:
# место для ответа


Используйте этот же двумерный массив и вычислите стандартное отклонение его элементов.
Ожидаемый результат: Стандартное отклонение элементов массива.



In [ ]:
# место для ответа


Найдите минимальное и максимальное значение, а также стандартное отклонение вдоль каждого столбца двумерного массива.
Ожидаемый результат: Минимальное и максимальное значение, а также стандартное отклонение для каждого столбца массива.

In [ ]:
# место для ответа


# Задача 5: Сортировка и нахождение уникальных значений с помощью NumPy

NumPy предлагает функции для сортировки элементов массива и нахождения уникальных значений. Ваша задача - использовать эти функции для работы с данными в массивах.

Создайте одномерный массив из 10 случайных целых чисел от 1 до 20. Отсортируйте этот массив в порядке возрастания.
Ожидаемый результат: Отсортированный массив из 10 случайных чисел.

In [ ]:
# место для ответа


Используя тот же одномерный массив, найдите все уникальные элементы этого массива.
Ожидаемый результат: Массив, содержащий все уникальные элементы исходного массива.

In [ ]:
# место для ответа


# Задача 6: Использование операторов сравнения и тестирование значений с NumPy

NumPy предоставляет операторы для сравнения элементов массива и проверки определенных условий. Ваша задача - использовать эти функции для анализа данных в массивах.

Создайте одномерный массив из 10 случайных чисел от 1 до 100. Создайте булев массив, который будет содержать `True` для всех элементов исходного массива, которые больше 50, и `False` - для всех остальных.
Ожидаемый результат: Булев массив размером 10.

In [ ]:
# место для ответа


Используя созданный булев массив, выберите из исходного массива только те элементы, которые больше 50.
Ожидаемый результат: Массив элементов исходного массива, которые больше 50.

In [ ]:
# место для ответа


# Бонус задание

Создайте двумерный массив размером 5x5 из случайных чисел от 1 до 50. Создайте булев массив, который будет содержать True для всех элементов исходного массива, которые четные, и False - для всех остальных.
Ожидаемый результат: Булев массив размером 5x5.

In [ ]:
# место для ответа


Используя созданный булев массив, выберите из исходного массива только те элементы, которые четные.
Ожидаемый результат: Массив элементов исходного массива, которые четные.

In [ ]:
# место для ответа
